# Generated by Django 4.2.19 on 2025-02-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
